version: "3.8"

services:
    # 1. FastAPI Backend Service
    backend:
        build:
            context: ./backend
        restart: always
        env_file:
            - ./backend/.env
        volumes:
            - ./backend:/app
        depends_on:
            - db
        networks:
            - app-network

    # 2. Next.js Frontend Service
    frontend:
        build:
            context: ./frontend
        restart: always
        volumes:
            - ./frontend:/app
            - /app/node_modules
            - /app/.next
        environment:
            # This is the internal URL for the Next.js server to proxy requests to the backend.
            - BACKEND_API_URL=http://backend:8000
        networks:
            - app-network
        ports:
            - "3000:3000"

    # 3. PostgreSQL Database Service
    db:
        image: postgres:15-alpine
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=capmatch_cache
        networks:
            - app-network
        ports:
            - "5432:5432"

volumes:
    postgres_data:

networks:
    app-network:
        driver: bridge
